### ISSUE TITLE
Agent Tool: Draw images with Dalle

### ISSUE THREAD

**Issue by ozramos** [ozramos/modelprompter#23]
Goal: Learn when to generate images, and put it in markdown

# Tasks
- [ ] Learn how LangChain Tools work
- [ ] Use OpenAI's image generation tool
- [ ] Display images inside markdown responses (or even as only response)

# Agent Ideas
- [ ] Haikus: create a markdown table, on one side put a haiku and on another an image

**Comment by ozramos** [comment]
Closing for now and consolidating tasks directly on ModelPrompter.com. We'll use issues for active tasks instead
