### ISSUE TITLE
Let's add iFramely support to autoexpand links/images within messages

### ISSUE THREAD

**Issue by ozramos** [ozramos/modelprompter#26]
Goal: Have link and image previews, as well as embedded tweets, videos, and iframes

# Notes
- Paid service: https://iframely.com/
- Self hosted service: https://github.com/itteco/iframely

# Tasks
- [ ] Gather all links in a message into array
- [ ] Parse each link as oEmbed and stack to end of message (or display in grid)
- [ ] Add (x) to disable link preview (like in discord)
- [ ] Setup local iframely service
- [ ] Handle parsing
- [ ] .env variables to customize service
- [ ] Add a new Settings Tab to update the service once it's built

**Comment by ozramos** [comment]
Closing for now and consolidating tasks directly on ModelPrompter.com. We'll use issues for active tasks instead
