### ISSUE TITLE
Let's find a workaround LLM token length errors

### ISSUE THREAD

**Issue by ozramos** [ozramos/modelprompter#39]
**Error message:** This model's maximum context length is 4097 tokens. However, your messages resulted in 12630 tokens. Please reduce the length of the messages

## Phase 1
- [ ] Count number of tokens
- [ ] For now, clip the tokens
- [ ] Show notification about context length (maybe linking to the card?)

## Phase 2
- [ ] Optional to clipping, have LLM summarize chunks recursively until all the content fits into the context length
