### ISSUE TITLE
Add ability to edit messages

### ISSUE THREAD

**Issue by ozramos** [ozramos/modelprompter#6]
Goal: Since the chat history serves as agent memory, it can be useful to edit them, for example, to add context, improve a prompt, etc

# Tasks
- [x] Right click to show context menu
- [x] Delete message
- [x] Edit message

# Retry
- [x] Add retry UI
- [x] Send history up to that message
- [x] Replace message
